In [1]:
!python -m spacy download en_core_web_md
!pip install -q streamlit
!npm install localtunnel

Collecting en-core-web-md==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.7.1/en_core_web_md-3.7.1-py3-none-any.whl (42.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 13.0 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /usr/local/lib/python3.10/dist-packages (from en-core-web-md==3.7.1) (3.7.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.2.3)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.9.4)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (6.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.66.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.31.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.6.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.1.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (24.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.3.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.25.2)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.3 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.16.3)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.10.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2024.2.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.1.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.10.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.1.7)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.4.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.1.5)
Installing collected packages: en-core-web-md
Successfully installed en-core-web-md-3.7.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 22.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 16.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 38.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.0/83.0 kB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 5.9 MB/s eta 0:00:00
npm WARN saveError ENOENT: no such file or directory, open '/content/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/content/package.json'
npm WARN content No description
npm WARN content No repository field.
npm WARN content No README data
npm WARN content No license field.

+ localtunnel@2.0.2
added 22 packages from 22 contributors and audited 22 packages in 2.128s

3 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

### Model Training Clawset Product Recommendation System

In [30]:
# import spacy
# from sklearn.metrics.pairwise import cosine_similarity
# import pandas as pd
# # Load spaCy model
# nlp = spacy.load("en_core_web_md")
# df=pd.read_csv('/content/Clawset_Dataset.csv',delimiter=',')

In [31]:
# # Preprocess and vectorize product descriptions
# processed_descriptions = [nlp(desc.lower()) for desc in df['Description']]

# # Compute similarity matrix
# similarity_matrix = cosine_similarity([doc.vector for doc in processed_descriptions])

# # Generate recommendations
# def get_recommendations(query, k=5):
#     query_doc = nlp(query.lower())
#     query_vector = query_doc.vector
#     sim_scores = cosine_similarity([query_vector], [doc.vector for doc in processed_descriptions])[0]
#     top_indices = sim_scores.argsort()[-k:][::-1]  # Get top k similar descriptions
#     recommendations = [(df.iloc[i]['Description'], sim_scores[i]) for i in top_indices]
#     return recommendations

In [32]:
# # Example usage
# query = "Color Collar"
# recommendations = get_recommendations(query)
# print("Top 5 Recommendations based on '{}' :\n".format(query))
# for rec in recommendations:
#     print("Product Description:", rec[0])
#     print("Similarity Score:", rec[1])
#     print()

In [33]:
# Save DataFrame to pickle
# df.to_pickle("clawset_product_descriptions.pkl")
# nlp.to_disk("clawset_spacy_model")

In [34]:
# !zip -r /content/clawset_spacy_model.zip /content/clawset_spacy_model

### Streamlit App for Recommendation System

In [37]:
%%writefile app.py
import streamlit as st
import spacy
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

#nlp = spacy.load("clawset_spacy_model")
nlp = spacy.load("en_core_web_md")
df = pd.read_pickle("clawset_product_descriptions.pkl")

# Preprocess and vectorize product descriptions
processed_descriptions = [nlp(desc.lower()) for desc in df['Description']]

# Compute similarity matrix
similarity_matrix = cosine_similarity([doc.vector for doc in processed_descriptions])

# Generate recommendations
def get_recommendations(query, k=5):
    if query:
      query_doc = nlp(query.lower())
      query_vector = query_doc.vector
      sim_scores = cosine_similarity([query_vector], [doc.vector for doc in processed_descriptions])[0]
      top_indices = sim_scores.argsort()[-k:][::-1]  # Get top k similar descriptions

      recommendations = [(df.iloc[i]['Description'], sim_scores[i]) for i in top_indices]
      return recommendations
    else:
      return []


st.title('Product Recommendation System')
query=st.text_input('Search',placeholder='Enter Products')

# recommended_products = get_recommendations(query)
#for product in recommended_products:
#    st.write(product)

if query:
    recommended_products = get_recommendations(query)
    if recommended_products:
        for product in recommended_products:
            st.write(product)
    else:
        st.write("No recommendations found.")

Overwriting app.py

In [ ]:
# !streamlit run /content/app.py &>/content/logs.txt & npx localtunnel --port 8501 & curl ipv4.icanhazip.com

34.123.134.195
npx: installed 22 in 2.174s
your url is: https://spicy-banks-tease.loca.lt

In [2]:
import pandas as pd
df1 = pd.read_pickle('clawset_product_descriptions.pkl')
df2 = pd.read_pickle('product_df.pkl')

In [3]:
df1

    Categories                                 Description
0          Bed          Two-tone square pet bed Light Blue
1          Bed                Two-tone square pet bed Pink
2          Bed               Two-tone square pet bed Brown
3          Bed  Spoiled Baby two-tone square pet bed  Blue
4          Bed  Spoiled Baby two-tone square pet bed  Pink
..         ...                                         ...
120        NaN                  Life Jacket- Bee - Yellow
121        NaN                Birthday baby- Collar- Pink
122        NaN                Birthday baby- Collar- Blue
123        NaN            Birthday baby - Party hat- Pink
124        NaN            Birthday baby - Party hat- Blue

[125 rows x 2 columns]

In [5]:
df2

    Categories                                 Description
0          Bed          Two-tone square pet bed Light Blue
1          Bed                Two-tone square pet bed Pink
2          Bed               Two-tone square pet bed Brown
3          Bed  Spoiled Baby two-tone square pet bed  Blue
4          Bed  Spoiled Baby two-tone square pet bed  Pink
..         ...                                         ...
120        NaN                  Life Jacket- Bee - Yellow
121        NaN                Birthday baby- Collar- Pink
122        NaN                Birthday baby- Collar- Blue
123        NaN            Birthday baby - Party hat- Pink
124        NaN            Birthday baby - Party hat- Blue

[125 rows x 2 columns]

# processing

In [2]:
import pandas as pd


df1 = pd.read_pickle('clawset_product_descriptions.pkl')
df1.head()

  Categories                                 Description
0        Bed          Two-tone square pet bed Light Blue
1        Bed                Two-tone square pet bed Pink
2        Bed               Two-tone square pet bed Brown
3        Bed  Spoiled Baby two-tone square pet bed  Blue
4        Bed  Spoiled Baby two-tone square pet bed  Pink

In [31]:
df1['Description'][0]

' Two-tone square pet bed Light Blue'

In [13]:
pip install gspread oauth2client

Collecting gspread
  Downloading gspread-6.1.2-py3-none-any.whl.metadata (11 kB)
Collecting oauth2client
  Downloading oauth2client-4.1.3-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: google-auth>=1.12.0 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from gspread) (2.29.0)
Collecting google-auth-oauthlib>=0.4.1 (from gspread)
  Downloading google_auth_oauthlib-1.2.1-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting httplib2>=0.9.1 (from oauth2client)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: pyasn1>=0.1.7 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from oauth2client) (0.6.0)
Requirement already satisfied: pyasn1-modules>=0.0.5 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from oauth2client) (0.4.0)
Requirement already satisfied: rsa>=3.1.4 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from oauth2client) (4.9)
Requirement already satisfied: six>=1.6.1 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from oauth2client) (1.16.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from google-auth>=1.12.0->gspread) (5.3.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from httplib2>=0.9.1->oauth2client) (3.1.1)
Requirement already satisfied: oauthlib>=3.0.0 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.2)
Requirement already satisfied: requests>=2.0.0 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in d:\python_enviroments\gen_env_3.11.5\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2024.2.2)
Downloading gspread-6.1.2-py3-none-any.whl (57 kB)
   ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
   --------------------- ------------------ 30.7/57.5 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 57.5/57.5 kB 1.5 MB/s eta 0:00:00
Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
   ---------------------------------------- 0.0/98.2 kB ? eta -:--:--
   ---------------------------------------- 98.2/98.2 kB 2.8 MB/s eta 0:00:00
Downloading google_auth_oauthlib-1.2.1-py2.py3-none-any.whl (24 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
   ---------------------------------------- 0.0/96.9 kB ? eta -:--:--
   ---------------------------------------- 96.9/96.9 kB 5.8 MB/s eta 0:00:00
Installing collected packages: httplib2, oauth2client, google-auth-oauthlib, gspread
Successfully installed google-auth-oauthlib-1.2.1 gspread-6.1.2 httplib2-0.22.0 oauth2client-4.1.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
# Remove 'Size M' or 'Size L'
import re

'Birthday baby - Party hat- Pink'

In [39]:
# url = "https://docs.google.com/spreadsheets/d/1pyY9KXof5Zs76HSxyYF0DRBJxATyKgmLDFpS82jjj3o/edit?gid=1324926915#gid=1324926915"
df = pd.read_csv('Master products list(USD) - Clawset Products list.csv')
# df = pd.read_csv(url, sep=',')
# df = pd.read_csv(url, error_bad_lines=False)
# df = pd.read_csv(url, quoting=csv.QUOTE_NONE, error_bad_lines=False)
# df = pd.read_csv(url, dtype=str)
# chunks = pd.read_csv(url, chunksize=1000)

In [40]:
# df = df[['SKU', 'Products name (Eng)', 'Categories']]
# df.head()
# df['']

def clean_text(text):
    # text = "Birthday baby - Party hat- Pink, Size M"
    text = re.sub(r', Size [ML]', '', text)
    
    # Remove special characters like \n
    text = re.sub(r'[\n]', '', text)
    
    # Split the cleaned text into separate lines again for readability
    text = re.sub(r'(\d{3})', r'\n\1', text).strip()
    text = re.sub(r'["\,]', ' ', text)
    return text

df['Products name (Eng)'] = df['Products name (Eng)'].apply(clean_text)
df['Products name (Eng)']

0       Tie-dye-patterned couple shirts for Owner   B...
1       Tie-dye-patterned couple shirts for Owner   B...
2       Tie-dye-patterned couple shirts for Owner    ...
3       Tie-dye-patterned couple shirts for Owner   K...
4       Tie-dye-patterned couple shirts for Owner   K...
                             ...
398                      Birthday baby - Party hat- Pink
399                      Birthday baby - Party hat- Pink
400              Birthday baby - Party hat- Blue  Size S
401                      Birthday baby - Party hat- Blue
402                      Birthday baby - Party hat- Blue
Name: Products name (Eng), Length: 403, dtype: object

In [41]:
df['Products name (Eng)'][0]

' Tie-dye-patterned couple shirts for Owner   Bupphahgaree  Orange'

In [43]:
df = df[['SKU', 'Products name (Eng)', 'Categories']]
df

             SKU                                Products name (Eng) Categories
0    OTS-02-00LI   Tie-dye-patterned couple shirts for Owner   B...      Shirt
1    OTS-02-0XLI   Tie-dye-patterned couple shirts for Owner   B...      Shirt
2    OTS-02-3XLI   Tie-dye-patterned couple shirts for Owner    ...      Shirt
3    OTS-02-00MC   Tie-dye-patterned couple shirts for Owner   K...      Shirt
4    OTS-02-00LC   Tie-dye-patterned couple shirts for Owner   K...      Shirt
..           ...                                                ...        ...
398  OHA-74-00MJ                    Birthday baby - Party hat- Pink        Hat
399  OHA-74-00LJ                    Birthday baby - Party hat- Pink        Hat
400  OHA-74-00SC            Birthday baby - Party hat- Blue  Size S        Hat
401  OHA-74-00MC                    Birthday baby - Party hat- Blue        Hat
402  OHA-74-00LC                    Birthday baby - Party hat- Blue        Hat

[403 rows x 3 columns]

In [45]:
df.to_pickle("./updated_df_V2.pkl")

# Data Creation

In [34]:
product_df=pd.read_csv("Master products list(USD) - Clawset Products list.csv", encoding='latin')
product_df.head()

,Collection,SKU,Image,Barcode,Products Name (TH),Products name (Eng),à¸£à¸²à¸à¸²à¸à¸²à¸¢à¹à¸à¸°à¸à¸³,RSP,à¸£à¸²à¸à¸²à¸à¸¸à¸,Color,...,Price before\nVAT (USD).2,Vat 7%.5,Price \nVAT included (USD).2,GP%\nMOQ : \n101,Categories,Sub Category,Description (à¸ à¸²à¸©à¸²à¹à¸à¸¢),Description,Ratings,Shelf Life \n(Year)
0,Tie Dye Patterned \nCouple Pet and Parent \nTh...,OTS-02-00LI,NaN,8859771509579,à¹à¸ªà¸·à¹à¸­à¸à¸ - à¹à¸ªà¸·à¹à¸­à¸à¸¹à...,"""Tie-dye-patterned couple\n shirts for Owner"" ...",690.0,19.99,310.3,Orange,...,11.98,0.84,12.8,35%,Shirt,NaN,à¸à¸à¸à¸·à¹à¸­à¸à¸¹à¹à¸¥à¸à¸à¸±à¸à¸à...,Unleash your inner artist spirit and elevate y...,5,2.0
1,NaN,OTS-02-0XLI,NaN,8859771509715,à¹à¸ªà¸·à¹à¸­à¸à¸ - à¹à¸ªà¸·à¹à¸­à¸à¸¹à...,"""Tie-dye-patterned couple\n shirts for Owner"" ...",690.0,19.99,310.3,Orange,...,11.98,0.84,12.8,35%,Shirt,NaN,NaN,NaN,5,2.0
2,NaN,OTS-02-3XLI,NaN,8859771509807,à¹à¸ªà¸·à¹à¸­à¸à¸ - à¹à¸ªà¸·à¹à¸­à¸à¸¹à...,"""Tie-dye-patterned couple\n shirts for Owner ""...",690.0,19.99,270.0,Orange,...,11.98,0.84,12.8,35%,Shirt,NaN,NaN,NaN,5,2.0
3,NaN,OTS-02-00MC,NaN,8859771509623,à¹à¸ªà¸·à¹à¸­à¸à¸ - à¹à¸ªà¸·à¹à¸­à¸à¸¹à...,"""Tie-dye-patterned couple\n shirts for Owner"" ...",690.0,19.99,310.3,Blue,...,11.98,0.84,12.8,35%,Shirt,NaN,NaN,NaN,5,2.0
4,NaN,OTS-02-00LC,NaN,8859771509555,à¹à¸ªà¸·à¹à¸­à¸à¸ - à¹à¸ªà¸·à¹à¸­à¸à¸¹à...,"""Tie-dye-patterned couple\n shirts for Owner"" ...",690.0,19.99,290.0,Blue,...,11.98,0.84,12.8,35%,Shirt,NaN,NaN,NaN,5,2.0

In [35]:
product_df=product_df[['SKU', 'Categories','Products name (Eng)']]
product_df.rename(columns = {'Products name (Eng)':'Description'}, inplace = True)

product_df

             SKU Categories                                        Description
0    OTS-02-00LI      Shirt  "Tie-dye-patterned couple\n shirts for Owner" ...
1    OTS-02-0XLI      Shirt  "Tie-dye-patterned couple\n shirts for Owner" ...
2    OTS-02-3XLI      Shirt  "Tie-dye-patterned couple\n shirts for Owner "...
3    OTS-02-00MC      Shirt  "Tie-dye-patterned couple\n shirts for Owner" ...
4    OTS-02-00LC      Shirt  "Tie-dye-patterned couple\n shirts for Owner" ...
..           ...        ...                                                ...
398  OHA-74-00MJ        Hat            Birthday baby - Party hat- Pink, Size M
399  OHA-74-00LJ        Hat            Birthday baby - Party hat- Pink, Size L
400  OHA-74-00SC        Hat            Birthday baby - Party hat- Blue, Size S
401  OHA-74-00MC        Hat            Birthday baby - Party hat- Blue, Size M
402  OHA-74-00LC        Hat            Birthday baby - Party hat- Blue, Size L

[403 rows x 3 columns]

In [36]:
# product_df['Description']=product_df['Products name (Eng)']

# Define a list of keywords to remove
keywords_to_remove = ['"','\n'
                         ,', Size S',', Size S2', ', Size M', ', Size M2',', Size L',', Size XL',', Size 2XL', ', Size 3XL', ', Size 4XL',', Size XS'
                         ,',Size S', ',Size M', ',Size L',',Size XL',',Size 2XL', ',Size 3XL', ',Size 4XL',',Size XS'
                         , ' Size S', ' Size M', ' Size L', ' Size XL', ' Size 2XL', ' Size 3XL', ' Size 4XL',', Size  XL',', Size 2 XL',', SizeM'
                         ,', Size 1', ', Size 2', ', Size 3',', Size 4',', Size 5', ', Size 6', ', Size 7',', Size 8',', Size 9', ', Size 10'
                         ,', Size 11',', Size 12',', Size 13', ', Size 14', ', Size 15',', Size 16',', Size 17'                   ] 
for keyword in keywords_to_remove:
    product_df['Description'] = product_df['Description'].str.replace(keyword, ' ')

In [37]:
keywords_to_remove =[', 1',', 2',', 3',', 4',', 5',', 6',', 7',', 8',', 9',', 10',', 11',', 12',', 13',', 14',', 15',', 16',', 18',', 17',
                     ' 1',' 2',' 3','4',' 5',' 6',
                     ', S',', M',', L',', XL']
for keyword in keywords_to_remove:
    product_df['Description'] = product_df['Description'].str.replace(keyword, ' ')

In [40]:
product_df = product_df.drop_duplicates(subset=['Description'])
product_df

,SKU,Categories,Description
0,OTS-02-00LI,Shirt,Tie-dye-patterned couple shirts for Owner ...
2,OTS-02-3XLI,Shirt,Tie-dye-patterned couple shirts for Owner ...
3,OTS-02-00MC,Shirt,Tie-dye-patterned couple shirts for Owner ...
7,OTS-02-00ML,Shirt,Tie-dye-patterned couple shirts for Owner ...
11,OTS-02-00MG,Shirt,Tie-dye-patterned couple shirts for Owner Na...
...,...,...,...
383,SLF-10-0XSF,Life Jacket,Life Jacket- Bee - Yellow
389,OCO-03-00SJ,Collar,Birthday baby- Collar- Pink
393,OCO-03-00SC,Collar,Birthday baby- Collar- Blue
397,OHA-74-00SJ,Hat,Birthday baby - Party hat- Pink
400,OHA-74-00SC,Hat,Birthday baby - Party hat- Blue

In [41]:
product_df.to_pickle('clawset_product_descriptions2.pkl')